{% set name = "typical" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typical-{{ version }}.tar.gz
  sha256: 9fc83f451ae939f63f7e3b27c1dfc384d174c932a170e58484effd1cdbddc499

build:
  number: 0
  noarch: python
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.7
  run:
    - future_typing >=0.4.1,<0.5.0
    - inflection >=0.5,<0.6
    - mypy
    - pendulum >=2.1,<3.0
    - python >=3.7
    - typing_extensions >=3.10.0,<4.0.0

test:
  imports:
    - typic
    - typic.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seandstewart/typical
  summary: "Typical: Python's Typing Toolkit."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
