{% set name = "typical" %}
{% set version = "2.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typical-{{ version }}.tar.gz
  sha256: 68efea206cb5239f9384bc930abf129630cc5670c5e042e2dbd89834ae50624e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - future_typing
    - inflection >=0.5,<0.6
    - mypy
    - pendulum >=2.1,<3.0
    - python >=3.6
    - typing_extensions

test:
  imports:
    - typic
    - typic.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seandstewart/typical
  summary: "Typical: Python's Typing Toolkit."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
