{% set name = "typical" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typical-{{ version }}.tar.gz
  sha256: fad5e8a2e7e2c8fcd5633a3166530eb42d8684544d713e0055f2f7402c4b7658

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - inflection >=0.3.1,<0.4.0
    - mypy
    - pendulum >=2.1,<3.0
    - python >=3.6
    - typing-extensions

test:
  imports:
    - typic
    - typic.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seandstewart/typical
  summary: "Typical: Python's Typing Toolkit."
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
